### ISSUE TITLE
Missing zip codes

### ISSUE THREAD

**Issue by Zhang** [blakek/us-zips#39]
I spot checked zip codes and noticed there are a few missing zip codes, such as: 99950

**Comment by blakek** [comment]
You're right. The README.md should be updated to call this out better.

The _reason_ they're missing is this is using [**ZIP Code Tabulation Areas**](https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html) by the US Census Bureau.

From the Census site:

> Some ZIP Codes represent very few addresses (sometimes only one) and therefore will not appear in the ZCTA universe.

There's other reasons a ZIP code wouldn't be listed here, but that's by far the most common reason I've noticed.

Looking at the population for 99950, I suspect it's missing for the reason above. It's likely the nearby 99918 was used for census purposes. For example if you look in Google Maps, [99918](https://www.google.com/maps/place/Ketchikan,+AK+99918/@55.9508961,-132.8758124,11z/data=!4m5!3m4!1s0x540f1959e524ea05:0xdf743a1b508a8675!8m2!3d55.9331022!4d-132.7482398) shows as expected, but [99950](https://www.google.com/maps/place/Ketchikan,+AK+99950/@55.9399991,-133.1887548,15z/data=!3m1!4b1!4m5!3m4!1s0x540efe2339e74e1d:0x628d786e53393a8a!8m2!3d55.94!4d-133.1800001) shows a staffing office location.

However, if you know of a better list of ZIP codes, I'd be interested in using it! Ones I looked for before using the ZCTA list had at least one of these issues:

- not open-source
- expensive
- outdated or mixes outdated information with updated (populated, changed ZIP show in wrong location)
